# Generated by Django 4.1.5 on 2023-05-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='content',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
