# Generated by Django 4.1.5 on 2023-05-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_alter_course_program_alter_forum_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
