# Generated by Django 4.1.5 on 2023-05-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filep',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
