# Generated by Django 4.1.5 on 2023-05-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_post_filep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='filep',
            new_name='filec',
        ),
    ]
