# Generated by Django 4.1.5 on 2023-05-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_rename_filep_post_filec'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='assignment',
            field=models.BooleanField(default=False),
        ),
    ]
