# Generated by Django 4.1.5 on 2023-05-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_alter_post_filec'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
