# Generated by Django 4.1.5 on 2023-06-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_assignment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='is_active',
        ),
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.FloatField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.FloatField(max_length=4, null=True),
        ),
    ]
