# Generated by Django 4.1.5 on 2023-06-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_remove_grade_is_active_assignment_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_professor',
        ),
    ]
