# Generated by Django 4.1.5 on 2023-06-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_remove_grade_grade_number_remove_user_is_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students',
            new_name='members',
        ),
    ]
