# Generated by Django 4.1.5 on 2023-06-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0015_rename_students_course_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='members',
            new_name='students',
        ),
    ]
