# Generated by Django 4.1.5 on 2023-06-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0017_remove_grade_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
