# Generated by Django 4.1.5 on 2023-06-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0018_alter_course_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
